package sell.dao.DO;

import org.apache.ibatis.annotations.Param;
import sell.pojo.RerationInfo;

import java.util.List;

public interface RerationInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reration_info
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(@Param("uId") Long uId, @Param("rUId") Long rUId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reration_info
     *
     * @mbggenerated
     */
    int insert(RerationInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reration_info
     *
     * @mbggenerated
     */
    RerationInfo selectByPrimaryKey(@Param("uId") Long uId, @Param("rUId") Long rUId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reration_info
     *
     * @mbggenerated
     */
    List<RerationInfo> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reration_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(RerationInfo record);

    //查询指定用户的所有联系人
    List<RerationInfo> selectAllByUID(@Param("uId") Long uId);

}