package sell.pojo;

import java.io.Serializable;
import java.util.Date;

public class FightInfo implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fight_info.fight_id
     *
     * @mbggenerated
     */
    private Long fightId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fight_info.fight_no
     *
     * @mbggenerated
     */
    private String fightNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fight_info.departure
     *
     * @mbggenerated
     */
    private String departure;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fight_info.destination
     *
     * @mbggenerated
     */
    private String destination;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fight_info.departure_time
     *
     * @mbggenerated
     */
    private Date departureTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fight_info.destination_time
     *
     * @mbggenerated
     */
    private Date destinationTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fight_info.fight_company_id
     *
     * @mbggenerated
     */
    private Long fightCompanyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fight_info.fight_type
     *
     * @mbggenerated
     */
    private String fightType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fight_info.fight_pay
     *
     * @mbggenerated
     */
    private Long fightPay;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fight_info.fight_num
     *
     * @mbggenerated
     */
    private Long fightNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fight_info.ticket_type_id
     *
     * @mbggenerated
     */
    private Long ticketTypeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fight_info.status
     *
     * @mbggenerated
     */
    private Byte status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fight_info.creat_time
     *
     * @mbggenerated
     */
    private Date creatTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fight_info.modfiy_time
     *
     * @mbggenerated
     */
    private Date modfiyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table fight_info
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fight_info.fight_id
     *
     * @return the value of fight_info.fight_id
     *
     * @mbggenerated
     */
    public Long getFightId() {
        return fightId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fight_info.fight_id
     *
     * @param fightId the value for fight_info.fight_id
     *
     * @mbggenerated
     */
    public void setFightId(Long fightId) {
        this.fightId = fightId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fight_info.fight_no
     *
     * @return the value of fight_info.fight_no
     *
     * @mbggenerated
     */
    public String getFightNo() {
        return fightNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fight_info.fight_no
     *
     * @param fightNo the value for fight_info.fight_no
     *
     * @mbggenerated
     */
    public void setFightNo(String fightNo) {
        this.fightNo = fightNo == null ? null : fightNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fight_info.departure
     *
     * @return the value of fight_info.departure
     *
     * @mbggenerated
     */
    public String getDeparture() {
        return departure;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fight_info.departure
     *
     * @param departure the value for fight_info.departure
     *
     * @mbggenerated
     */
    public void setDeparture(String departure) {
        this.departure = departure == null ? null : departure.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fight_info.destination
     *
     * @return the value of fight_info.destination
     *
     * @mbggenerated
     */
    public String getDestination() {
        return destination;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fight_info.destination
     *
     * @param destination the value for fight_info.destination
     *
     * @mbggenerated
     */
    public void setDestination(String destination) {
        this.destination = destination == null ? null : destination.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fight_info.departure_time
     *
     * @return the value of fight_info.departure_time
     *
     * @mbggenerated
     */
    public Date getDepartureTime() {
        return departureTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fight_info.departure_time
     *
     * @param departureTime the value for fight_info.departure_time
     *
     * @mbggenerated
     */
    public void setDepartureTime(Date departureTime) {
        this.departureTime = departureTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fight_info.destination_time
     *
     * @return the value of fight_info.destination_time
     *
     * @mbggenerated
     */
    public Date getDestinationTime() {
        return destinationTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fight_info.destination_time
     *
     * @param destinationTime the value for fight_info.destination_time
     *
     * @mbggenerated
     */
    public void setDestinationTime(Date destinationTime) {
        this.destinationTime = destinationTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fight_info.fight_company_id
     *
     * @return the value of fight_info.fight_company_id
     *
     * @mbggenerated
     */
    public Long getFightCompanyId() {
        return fightCompanyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fight_info.fight_company_id
     *
     * @param fightCompanyId the value for fight_info.fight_company_id
     *
     * @mbggenerated
     */
    public void setFightCompanyId(Long fightCompanyId) {
        this.fightCompanyId = fightCompanyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fight_info.fight_type
     *
     * @return the value of fight_info.fight_type
     *
     * @mbggenerated
     */
    public String getFightType() {
        return fightType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fight_info.fight_type
     *
     * @param fightType the value for fight_info.fight_type
     *
     * @mbggenerated
     */
    public void setFightType(String fightType) {
        this.fightType = fightType == null ? null : fightType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fight_info.fight_pay
     *
     * @return the value of fight_info.fight_pay
     *
     * @mbggenerated
     */
    public Long getFightPay() {
        return fightPay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fight_info.fight_pay
     *
     * @param fightPay the value for fight_info.fight_pay
     *
     * @mbggenerated
     */
    public void setFightPay(Long fightPay) {
        this.fightPay = fightPay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fight_info.fight_num
     *
     * @return the value of fight_info.fight_num
     *
     * @mbggenerated
     */
    public Long getFightNum() {
        return fightNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fight_info.fight_num
     *
     * @param fightNum the value for fight_info.fight_num
     *
     * @mbggenerated
     */
    public void setFightNum(Long fightNum) {
        this.fightNum = fightNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fight_info.ticket_type_id
     *
     * @return the value of fight_info.ticket_type_id
     *
     * @mbggenerated
     */
    public Long getTicketTypeId() {
        return ticketTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fight_info.ticket_type_id
     *
     * @param ticketTypeId the value for fight_info.ticket_type_id
     *
     * @mbggenerated
     */
    public void setTicketTypeId(Long ticketTypeId) {
        this.ticketTypeId = ticketTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fight_info.status
     *
     * @return the value of fight_info.status
     *
     * @mbggenerated
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fight_info.status
     *
     * @param status the value for fight_info.status
     *
     * @mbggenerated
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fight_info.creat_time
     *
     * @return the value of fight_info.creat_time
     *
     * @mbggenerated
     */
    public Date getCreatTime() {
        return creatTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fight_info.creat_time
     *
     * @param creatTime the value for fight_info.creat_time
     *
     * @mbggenerated
     */
    public void setCreatTime(Date creatTime) {
        this.creatTime = creatTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fight_info.modfiy_time
     *
     * @return the value of fight_info.modfiy_time
     *
     * @mbggenerated
     */
    public Date getModfiyTime() {
        return modfiyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fight_info.modfiy_time
     *
     * @param modfiyTime the value for fight_info.modfiy_time
     *
     * @mbggenerated
     */
    public void setModfiyTime(Date modfiyTime) {
        this.modfiyTime = modfiyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fight_info
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", fightId=").append(fightId);
        sb.append(", fightNo=").append(fightNo);
        sb.append(", departure=").append(departure);
        sb.append(", destination=").append(destination);
        sb.append(", departureTime=").append(departureTime);
        sb.append(", destinationTime=").append(destinationTime);
        sb.append(", fightCompanyId=").append(fightCompanyId);
        sb.append(", fightType=").append(fightType);
        sb.append(", fightPay=").append(fightPay);
        sb.append(", fightNum=").append(fightNum);
        sb.append(", ticketTypeId=").append(ticketTypeId);
        sb.append(", status=").append(status);
        sb.append(", creatTime=").append(creatTime);
        sb.append(", modfiyTime=").append(modfiyTime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}