package sell.pojo;

import java.io.Serializable;
import java.util.Date;

public class Message implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.m_id
     *
     * @mbggenerated
     */
    private Long mId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.m_title
     *
     * @mbggenerated
     */
    private String mTitle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.m_question
     *
     * @mbggenerated
     */
    private String mQuestion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.m_answer
     *
     * @mbggenerated
     */
    private String mAnswer;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.q_user_id
     *
     * @mbggenerated
     */
    private Long qUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.a_user_id
     *
     * @mbggenerated
     */
    private Long aUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.q_user_name
     *
     * @mbggenerated
     */
    private String qUserName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.a_user_name
     *
     * @mbggenerated
     */
    private String aUserName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.q_time
     *
     * @mbggenerated
     */
    private Date qTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.a_time
     *
     * @mbggenerated
     */
    private Date aTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table message
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.m_id
     *
     * @return the value of message.m_id
     *
     * @mbggenerated
     */
    public Long getmId() {
        return mId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.m_id
     *
     * @param mId the value for message.m_id
     *
     * @mbggenerated
     */
    public void setmId(Long mId) {
        this.mId = mId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.m_title
     *
     * @return the value of message.m_title
     *
     * @mbggenerated
     */
    public String getmTitle() {
        return mTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.m_title
     *
     * @param mTitle the value for message.m_title
     *
     * @mbggenerated
     */
    public void setmTitle(String mTitle) {
        this.mTitle = mTitle == null ? null : mTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.m_question
     *
     * @return the value of message.m_question
     *
     * @mbggenerated
     */
    public String getmQuestion() {
        return mQuestion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.m_question
     *
     * @param mQuestion the value for message.m_question
     *
     * @mbggenerated
     */
    public void setmQuestion(String mQuestion) {
        this.mQuestion = mQuestion == null ? null : mQuestion.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.m_answer
     *
     * @return the value of message.m_answer
     *
     * @mbggenerated
     */
    public String getmAnswer() {
        return mAnswer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.m_answer
     *
     * @param mAnswer the value for message.m_answer
     *
     * @mbggenerated
     */
    public void setmAnswer(String mAnswer) {
        this.mAnswer = mAnswer == null ? null : mAnswer.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.q_user_id
     *
     * @return the value of message.q_user_id
     *
     * @mbggenerated
     */
    public Long getqUserId() {
        return qUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.q_user_id
     *
     * @param qUserId the value for message.q_user_id
     *
     * @mbggenerated
     */
    public void setqUserId(Long qUserId) {
        this.qUserId = qUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.a_user_id
     *
     * @return the value of message.a_user_id
     *
     * @mbggenerated
     */
    public Long getaUserId() {
        return aUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.a_user_id
     *
     * @param aUserId the value for message.a_user_id
     *
     * @mbggenerated
     */
    public void setaUserId(Long aUserId) {
        this.aUserId = aUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.q_user_name
     *
     * @return the value of message.q_user_name
     *
     * @mbggenerated
     */
    public String getqUserName() {
        return qUserName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.q_user_name
     *
     * @param qUserName the value for message.q_user_name
     *
     * @mbggenerated
     */
    public void setqUserName(String qUserName) {
        this.qUserName = qUserName == null ? null : qUserName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.a_user_name
     *
     * @return the value of message.a_user_name
     *
     * @mbggenerated
     */
    public String getaUserName() {
        return aUserName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.a_user_name
     *
     * @param aUserName the value for message.a_user_name
     *
     * @mbggenerated
     */
    public void setaUserName(String aUserName) {
        this.aUserName = aUserName == null ? null : aUserName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.q_time
     *
     * @return the value of message.q_time
     *
     * @mbggenerated
     */
    public Date getqTime() {
        return qTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.q_time
     *
     * @param qTime the value for message.q_time
     *
     * @mbggenerated
     */
    public void setqTime(Date qTime) {
        this.qTime = qTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.a_time
     *
     * @return the value of message.a_time
     *
     * @mbggenerated
     */
    public Date getaTime() {
        return aTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.a_time
     *
     * @param aTime the value for message.a_time
     *
     * @mbggenerated
     */
    public void setaTime(Date aTime) {
        this.aTime = aTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", mId=").append(mId);
        sb.append(", mTitle=").append(mTitle);
        sb.append(", mQuestion=").append(mQuestion);
        sb.append(", mAnswer=").append(mAnswer);
        sb.append(", qUserId=").append(qUserId);
        sb.append(", aUserId=").append(aUserId);
        sb.append(", qUserName=").append(qUserName);
        sb.append(", aUserName=").append(aUserName);
        sb.append(", qTime=").append(qTime);
        sb.append(", aTime=").append(aTime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}