package sell.pojo;

import java.io.Serializable;
import java.util.Date;

public class RerationInfo implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reration_info.u_id
     *
     * @mbggenerated
     */
    private Long uId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reration_info.r_u_id
     *
     * @mbggenerated
     */
    private Long rUId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reration_info.status
     *
     * @mbggenerated
     */
    private Byte status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reration_info.creat_time
     *
     * @mbggenerated
     */
    private Date creatTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reration_info.modify_time
     *
     * @mbggenerated
     */
    private Date modifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table reration_info
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reration_info.u_id
     *
     * @return the value of reration_info.u_id
     *
     * @mbggenerated
     */
    public Long getuId() {
        return uId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reration_info.u_id
     *
     * @param uId the value for reration_info.u_id
     *
     * @mbggenerated
     */
    public void setuId(Long uId) {
        this.uId = uId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reration_info.r_u_id
     *
     * @return the value of reration_info.r_u_id
     *
     * @mbggenerated
     */
    public Long getrUId() {
        return rUId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reration_info.r_u_id
     *
     * @param rUId the value for reration_info.r_u_id
     *
     * @mbggenerated
     */
    public void setrUId(Long rUId) {
        this.rUId = rUId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reration_info.status
     *
     * @return the value of reration_info.status
     *
     * @mbggenerated
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reration_info.status
     *
     * @param status the value for reration_info.status
     *
     * @mbggenerated
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reration_info.creat_time
     *
     * @return the value of reration_info.creat_time
     *
     * @mbggenerated
     */
    public Date getCreatTime() {
        return creatTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reration_info.creat_time
     *
     * @param creatTime the value for reration_info.creat_time
     *
     * @mbggenerated
     */
    public void setCreatTime(Date creatTime) {
        this.creatTime = creatTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reration_info.modify_time
     *
     * @return the value of reration_info.modify_time
     *
     * @mbggenerated
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reration_info.modify_time
     *
     * @param modifyTime the value for reration_info.modify_time
     *
     * @mbggenerated
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reration_info
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", uId=").append(uId);
        sb.append(", rUId=").append(rUId);
        sb.append(", status=").append(status);
        sb.append(", creatTime=").append(creatTime);
        sb.append(", modifyTime=").append(modifyTime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}